---
daemon:
  env:
    - name: BRANCH
      value: main
    - name: DIPPER_SSH_KEY
      value: vault:secret/data/honeydipper/git_keys#honeydipper-init
    - name: DIPPER_SSH_KEYFILE
      value: dummy
    - name: HD_REDIS_ADDR
      value: redis:6379
    - name: HD_REDIS_AUTH
      value: vault:secret/data/honeydipper/redis#auth
    - name: REPO
      value: git@github.com:Charles546/honeydipper-init.git
    - name: OLLAMA_HOST
      value: http://truenas.lan:30068
  image:
    repository: charleshoney/honeydipper
    tag: "CH-vault-03282025-3"
  pod_annotations:
    vault.security.banzaicloud.io/vault-addr: https://vault.m4cloud.duckdns.org:8200
    vault.security.banzaicloud.io/vault-skip-verify: "false"
  replicaCount: 2
  serviceAccountName: honeydipper

drivers:
  redis:
    local: false

